repository_type: pipeline
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/samurai_logo_mqc.png
    - assets/nf-core-samurai_logo_light.png
    - docs/images/nf-core-samurai_logo_light.png
    - docs/images/nf-core-samurai_logo_dark.png
    - docs/images/samurai_logo.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/ci.yml
    - .github/workflows/branch.yml
    - .github/workflows/nf-test.yml
    - .github/actions/get-shards/action.yml
    - .github/actions/nf-test/action.yml
    - nf-test.config
    - tests/default.nf.test
    - ro-crate-metadata.json
  included_configs: false
  files_unchanged:
    - .github/workflows/ci.yml
    - .github/workflows/branch.yml
    - .prettierignore
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  check_local_copy:
    - utils_nfschema_plugin
  readme:
    - nextflow_badge
    - nfcore_template_badge
  schema_params: false
  subworkflow_changes:
    - utils_nfschema_plugin
    - check_local_copy
  actions_ci: false
nf_core_version: 3.4.1
template:
  version: 1.3.0
