repository_type: pipeline
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/samurai_logo_mqc.png
    - assets/nf-core-samurai_logo_light.png
    - docs/images/nf-core-samurai_logo_light.png
    - docs/images/nf-core-samurai_logo_dark.png
    - docs/images/samurai_logo.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/ci.yml
    - .github/workflows/branch.yml
    - nf-test.config
    - .github/actions/nf-test/action.yml
    - .github/actions/get-shards/action.yml
    - .github/workflows/nf-test.yml
    - tests/default.nf.test
  files_unchanged:
    - .github/workflows/ci.yml
    - .github/workflows/branch.yml
    - lib/NfcoreTemplate.groovy
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  readme:
    - nextflow_badge
  schema_params: false
  subworkflow_changes:
    - utils_nfcore_pipeline
  actions_ci: false
  nf_test_content: false
  check_local_copy: false
nf_core_version: 3.4.1
